# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fbc8e3f1fcd4f61a0c402a47e87b55a01568ec9f0244b97b184a69ee2470ddcb29573ad9806d0bc953b6d9702d0710f93eb618a6f174664652d16334a37c7919

test:
  secret_key_base: 7c7411e884593436e94ba0e47f30205396551828b09ba73bdf460c35ab939737e45ffcc3fb2a6551d7afb6c4e649d25058ed2585f2fbac04c94425120ef88669

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
